.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH USB-CREATOR-GTK 8 "June  26, 2009" Ubuntu
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
usb-creator-gtk \- Ubuntu USB disk creation tool
.SH SYNOPSIS
.B usb-creator
.SH DESCRIPTION
\fBusb-creator-gtk\fP takes an Ubuntu CD or CD image file as input and writes it out in a usable form to a USB disk.
.SH OPTIONS
.TP
.B -s, --safe
Choose safer options when constructing the USB disk (may slow down the boot process).
.TP
.B -i, --iso <img>
Provide a source image (CD or raw disk) to pre-populate the UI.
.TP
.B -n, --not_persistent
Disable persistent setting by default in the UI.
.TP
.B -t, --trace
Create a ~/.usb-creator-kde.trace file.
.TP
.BR -h, --help
Print a summary of command line options and exit.
.TP
.BR --version
Print the current version and exit.
